#ifndef MOS6502_INSTRUCTIONS_HEADER
#define MOS6502_INSTRUCTIONS_HEADER

#include <cstdint>

namespace libemu::mos6502{

// TODO: After dummy reads, run command?

// Timing logic: https://www.zimmers.net/anonftp/pub/cbm/documents/chipdata/64doc
// Instructions: https://www.nesdev.org/wiki/Instruction_reference

#define MOS6502_ACCUMULATOR(cmd) ucode::READ_NEXT,   cmd
#define MOS6502_IMPLIED(cmd)     ucode::READ_NEXT,   cmd
#define MOS6502_IMMEDIATE(cmd)   ucode::FETCH_VALUE, cmd

#define MOS6502_ABSOLUTE_RD(cmd) ucode::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH, ucode::READ_ADDR, cmd
#define MOS6502_ABSOLUTE_RW(cmd) ucode::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH, ucode::READ_ADDR, ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_ABSOLUTE_WR(cmd) ucode::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH, cmd,              ucode::WRITE_ADDR

#define MOS6502_ZEROPAGE_RD(cmd) ucode::FETCH_ADDR, ucode::READ_ADDR, cmd
#define MOS6502_ZEROPAGE_RW(cmd) ucode::FETCH_ADDR, ucode::READ_ADDR, ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_ZEROPAGE_WR(cmd) ucode::FETCH_ADDR, cmd,              ucode::WRITE_ADDR

#define MOS6502_ZEROPAGEI_RD(cmd, reg) ucode::FETCH_ADDR, ucode::ADDR_P##reg, ucode::READ_ADDR, cmd
#define MOS6502_ZEROPAGEI_RW(cmd, reg) ucode::FETCH_ADDR, ucode::ADDR_P##reg, ucode::READ_ADDR, ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_ZEROPAGEI_WR(cmd, reg) ucode::FETCH_ADDR, ucode::ADDR_P##reg, cmd,              ucode::WRITE_ADDR

#define MOS6502_ABSOLUTEI_RD(cmd, reg) ucode::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH_P##reg, ucode::READ_ADDR,     ucode::PUNISH_PAGE, ucode::READ_ADDR,  cmd
#define MOS6502_ABSOLUTEI_RW(cmd, reg) ucode::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH_P##reg, ucode::READ_ADDR_FIX, ucode::READ_ADDR,   ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_ABSOLUTEI_WR(cmd, reg) ucdoe::FETCH_ADDR_LOW, ucode::FETCH_ADDR_HIGH_P##reg, ucode::READ_ADDR_FIX, cmd,                ucode::WRITE_ADDR

#define MOS6502_INDIRECTX_RD(cmd) ucode::FETCH_POINTER, ucode::ADDR_PX, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH, ucode::READ_ADDR, cmd
#define MOS6502_INDIRECTX_RW(cmd) ucode::FETCH_POINTER, ucode::ADDR_PX, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH, ucode::READ_ADDR, ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_INDIRECTX_WR(cmd) ucode::FETCH_POINTER, ucode::ADDR_PX, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH, cmd,              ucode::WRITE_ADDR

#define MOS6502_INDIRECTY_RD(cmd) ucode::FETCH_POINTER, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH_PY, ucode::READ_ADDR,     ucode::PUNISH_PAGE, cmd
#define MOS6502_INDIRECTY_RW(cmd) ucode::FETCH_POINTER, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH_PY, ucode::READ_ADDR_FIX, ucode::READ_ADDR,   ucode::WRITE_ADDR, cmd, ucode::WRITE_ADDR
#define MOS6502_INDIRECTY_WR(cmd) ucode::FETCH_POINTER, ucode::FETCH_EFF_ADDR_LOW, ucode::FETCH_EFF_ADDR_HIGH_PY, ucode::READ_ADDR_FIX, cmd,                ucode::WRITE_ADDR

enum class ucode : std::uint8_t{
    FETCH_OPCODE, 

    PUNISH_PAGE,
    READ_NEXT,
    ADDR_PX,
    ADDR_PY,
    READ_ADDR,
    
    FETCH_POINTER,
    FETCH_EFF_ADDR_LOW,
    FETCH_EFF_ADDR_HIGH_PY,
    FETCH_EFF_ADDR_HIGH,

    FETCH_VALUE,
    FETCH_ADDR,
    FETCH_ADDR_LOW,
    FETCH_ADDR_HIGH_PX,
    FETCH_ADDR_HIGH_PY,
    FETCH_ADDR_HIGH,

    WRITE_ADDR,

    INSTRUCTION, // Dummy value

    LDA, STA, LDX, STX, LDY, STY,
    TAX, TXA, TAY, TYA,
    ADC, SBC, INC, DEC, INX, DEX, INY, DEY,
    ASL, LSR, ROL, ROR,
    AND, ORA, EOR, BIT,
    CMP, CPX, CPY,
    BCC, BCS, BEQ, BNE, BPL, BMI, BVC, BVS,
    JMP, JSR, RTS, BRK, RTI,
    PHA, PLA, PHP, PLP, TXS, TSX,
    CLC, SEC, CLI, SEI, CLD, SED, CLV,
    NOP
};

static const ucode instructions[256][8] = {
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { MOS6502_IMMEDIATE(ucode::LDA) },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
};

}

#endif