#ifndef MOS6502_MICROCODE_HEADER
#define MOS6502_MICROCODE_HEADER

enum class MOS6502_uCode{
    DONE,

    FETCH_IMPLIED,
    FETCH_ACCUMULATOR,
    FETCH_IMMEDIATE,

    FETCH_ADDR,
    FETCH_ADDR_LOW,
    FETCH_ADDR_HIGH_PX,
    FETCH_ADDR_HIGH_PY,
    FETCH_ADDR_HIGH,

    FETCH_EFF_ADDR_LOW,
    FETCH_EFF_ADDR_HIGH_PY,
    FETCH_EFF_ADDR_HIGH,

    ADDR_PX,
    ADDR_PY,
    PUNISH_PAGE,
    READ_OPERAND,
    WRITE_OPERAND,

    INSTRUCTION_BEGIN,

    LDA, STA, LDX, STX, LDY, STY
};

static const MOS6502_uCode mos6502_ucode_instructions[256][10] = {
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::FETCH_EFF_ADDR_LOW, MOS6502_uCode::FETCH_EFF_ADDR_HIGH, MOS6502_uCode::STA }, // STA (Indirect,X)
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::STY }, // STY Zero Page
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::STA }, // STA Zero Page
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::STX }, // STX Zero Page
    {},
    {},
    {},
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::STY }, // STY Absolute
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::STA }, // STA Absolute
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::STX }, // STX Absolute
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::FETCH_EFF_ADDR_LOW, MOS6502_uCode::FETCH_EFF_ADDR_HIGH_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::STA }, // STA (Indirect),Y
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::STY }, // STY Zero Page,X
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::STA }, // STA Zero Page,X
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PY, MOS6502_uCode::STX }, // STX Zero Page,Y
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::STA }, // STA Absolute,Y
    {},
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PX, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::STA }, // STA Absolute,X
    {},
    {},
    { MOS6502_uCode::FETCH_IMMEDIATE, MOS6502_uCode::LDY }, // LDY Immediate
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::FETCH_EFF_ADDR_LOW, MOS6502_uCode::FETCH_EFF_ADDR_HIGH, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDA }, // LDA (Indirect,X)
    { MOS6502_uCode::FETCH_IMMEDIATE, MOS6502_uCode::LDX }, // LDX Immediate
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDY }, // LDY Zero Page
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDA }, // LDA Zero Page
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDX }, // LDX Zero Page
    {},
    {},
    { MOS6502_uCode::FETCH_IMMEDIATE, MOS6502_uCode::LDA }, // LDA Immediate
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDY }, // LDY Absolute
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDA }, // LDA Absolute
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDX }, // LDX Absolute
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::FETCH_EFF_ADDR_LOW, MOS6502_uCode::FETCH_EFF_ADDR_HIGH_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::LDA }, // LDA (Indirect),Y
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDY }, // LXY Zero Page,X
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PX, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDA }, // LDA Zero Page,X
    { MOS6502_uCode::FETCH_ADDR, MOS6502_uCode::ADDR_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::LDX }, // LDX Zero Page,Y
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::LDA }, // LDA Absolute,Y
    {},
    {},
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PX, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::LDY }, // LDY Absolute,X
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PX, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::LDA }, // LDA Absolute,X
    { MOS6502_uCode::FETCH_ADDR_LOW, MOS6502_uCode::FETCH_ADDR_HIGH_PY, MOS6502_uCode::READ_OPERAND, MOS6502_uCode::PUNISH_PAGE, MOS6502_uCode::LDX }, // LDX Absolute,Y
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
};

#endif